version: "3.3"
services:
  postgresql:
    image: postgres
    depends_on:
      - app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    image: krikey/app
    ports:
    - "8080:8080"
